---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-all
  namespace: cve-2022-0185-fix
spec:
  podSelector:
    matchLabels:
      k8s-app: cve-2022-0185-fix
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress:  []
---
apiVersion: "apps/v1"
kind: DaemonSet
metadata:
  name: cve-2022-0185-fix
  namespace: cve-2022-0185-fix
  labels:
    k8s-app: cve-2022-0185-fix
    version: 1v
spec:
  selector:
    matchLabels:
      k8s-app: cve-2022-0185-fix
  template:
    metadata:
      labels:
        k8s-app: cve-2022-0185-fix
    spec:
      hostPID: true
      containers:
      - name: cve-2022-0185-fix
        image: cr.yandex/crpjfmfou6gflobbfvfv/ubuntu-openssl:stable
        command: 
          - sh
          - -c
          - |
            while true; do
              kernel_value=$(sysctl kernel.unprivileged_userns_clone | cut -f 3 -d ' ')
              if [ $kernel_value -ne 0 ];
                then
                    echo "Fixing the kernel"
                    sysctl -w kernel.unprivileged_userns_clone=0
                else
                  echo "Doing Nothing as kernel is updated"
                fi
              sleep 30                
            done
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi          
        volumeMounts:
        - mountPath: /proc/
          name: proc
        - name: sbin
          mountPath: /usr/sbin
      volumes:
      - name: proc
        hostPath:
          path: /proc/
          type: Directory
      - name: sbin
        hostPath:
          path: /usr/sbin/
          type: Directory