apiVersion: v1
kind: ConfigMap
metadata:
  name: osquery-cm-startup
  namespace: osquery
data:
  startup.sh: |
    #!/bin/sh
    #check if osquery installed on host and then run osquery or install and run it on host
    #also copy config files
    ####
    ([ -f host/opt/osquery/bin/osqueryd ] && cp /var/config/osquery.example.conf /host/etc/osquery/osquery.conf; cp /opt/config/*.conf /host/opt/osquery/share/osquery/packs/; \
    chroot /host /opt/osquery/bin/osqueryd --verbose --disable_events=false --enable_file_events=true) \
    || mkdir /host/etc/osquery; mkdir -p /host/opt/osquery/share/osquery/packs/; mkdir -p /host/opt/osquery/bin/; mkdir -p /host/var/log/osquery \
    && cp /var/config/osquery.example.conf /host/etc/osquery/osquery.conf; cp /opt/config/*.conf /host/opt/osquery/share/osquery/packs/; cp /opt/osquery/bin/osqueryd /host/opt/osquery/bin/osqueryd \
    && chroot /host /opt/osquery/bin/osqueryd --verbose --disable_events=false --enable_file_events=true
