#cloud-config
#ssh_pwauth: no
users:
  - name: yc-user
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - "${ssh_key}"
  - name: ksc-ssh
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$rounds=4096$CI8Y8CUg/Fg6xD$JS8K7V3lO5ucoDzrb/JttJempKCK5hWxDWpZWVCryzvjyD/9YkdxTSOuT4q.KHcQHEflVTsGaaql0QBX2R3Yr/
runcmd:
  - sudo apt-get install perl -y
  - sudo wget https://secure.eicar.org/eicar.com.txt
      